language: java

sudo: required

services:
   - mongodb
   - docker
jdk:
  - oraclejdk8

after_success:
   - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" tilos.hu:5555
   - ./docker.sh

notifications:
  webhooks: $HUBOT_TRAVIS_URL
  on_start: true