language: java

jdk:
  - oraclejdk8

after_success:
- mkdir -p build/upload
- cp buid/libs/*.jar build/upload
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  acl: public_read
  local_dir: build/upload
  skip_cleanup: true


